config/routes.rb
OpenGovernment::Application.routes.draw do
  resources :blurbs

  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'sessions'
  }

  if ENV["SPLASH_AS_HOMEPAGE"]
    root to: 'pages#splash'
    get 'home' => 'pages#index'
  else
    root to: 'pages#index'
  end

  # generate a custom robots.txt
  get 'robots.:format' => 'robots#show'

  get 'widgets/builder' => 'pages#widget_builder'
  get 'splash' => 'pages#splash'
  get 'electeds' => 'pages#splash'
  get 'elected_signup' => 'pages#elected_signup'
  get 'about', to: 'pages#about'
  get 'support', to: 'pages#support'
  get 'faq', to: 'pages#faq'
  get 'honestads', to: 'pages#honestads'
  get 'map', to: 'pages#map'
  get 'terms-of-service', to: 'pages#terms_of_service'
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'candidates', to: 'pages#candidates', as: :candidates_page

  resources :users, only: [:show, :update] do
    member do
      get 'signatures'
    end
  end
  resources :signatures, only: :create
  resources :answers, only: [:create, :edit, :update]

  resources :identities, only: :update

  scope ':jurisdiction' do
    resources :bills, only: [:index, :show] do
      member do
        get 'sponsors'
      end
    end

    resources :people, only: [:index, :show, :update] do
      member do
        get 'bills'
        get 'committees'
        get 'votes'
        get 'ratings'
      end
    end

    resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'preview'
        get 'need_signatures'
        get 'have_answers'
        get 'need_answers'
        get 'recent'
      end

      resources :signatures, only: :index
    end

    resources :subjects, only: [:index, :show]

    match 'overview/lower' => 'pages#lower', as: :lower_overview, via: :get
    match 'overview/upper' => 'pages#upper', as: :upper_overview, via: :get
    match 'overview/bills' => 'pages#bills', as: :bills_overview, via: :get
    match 'overview/meetings' => 'pages#meetings', as: :meetings_overview, via: :get
    match 'overview/votes' => 'pages#key_votes', as: :key_votes_overview, via: :get

    get 'map', to: 'pages#map'

    resources :candidates
  end

  match 'email_upkeep' => 'email_upkeep#index', as: :email_upkeep, via: [:post]

  match 'locator' => 'pages#locator', as: :locator, via: [:get, :post]
  match 'identifier' => 'pages#identifier', as: :identifier, via: :get
  match 'contact_info' => 'pages#contact_info', as: :contact_info, via: :get
  match 'channel' => 'pages#channel', as: :channel, via: :get
  match 'people' => 'people#index', as: :unaffiliated_people, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'people/:id' => 'people#show', as: :unaffiliated_person, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'questions' => 'questions#index', as: :unaffiliated_questions, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'questions/:id' => 'questions#show', as: :unaffiliated_question, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match ':jurisdiction' => 'pages#overview', as: :jurisdiction, via: :get
end

app/models/person.rb
# Billy
class Person
  include Mongoid::Document

  # authorization based on roles
  # i.e. a user.can_respond_as?(person) to answer questions
  resourcify :user_roles, role_cname: 'UserRole'

  # The person's jurisdiction.
  belongs_to :metadatum, foreign_key: 'state'
  # Questions addressed to the person.
  has_many :questions

  # a user identified as the person
  # potentially elected official's staff would also have a user account
  # identified as the same person, thus has_many
  has_many :identities

  # candidates that are running against this person
  has_many :opponents, class_name: "Candidate", inverse_of: :current_office_holder

  # Popolo fields and aliases.
  field :full_name, type: String, as: :name
  field :leg_id, type: String, as: :slug
  field :last_name, type: String, as: :family_name
  field :first_name, type: String, as: :given_name
  field :middle_name, type: String, as: :additional_name
  field '+title', type: String, as: :honorific_prefix # always "" in OpenStates
  field :suffixes, type: String, as: :honorific_suffix
  field :email, type: String
  field '+gender', type: String, as: :gender
  field :photo_url, type: String, as: :image
  field :old_photo_urls, type: Array
  # @todo move chamber to legislator mixin
  # and refactor dependencies on chamber being present
  field :chamber, type: String

  # social media handling
  field :twitter_id, type: String
  # mainly to be used for quick look up, save as downcase
  field :additional_twitter_ids, type: Array

  # whether to show them on homepage or not
  # assumes only one person flagged featured
  field :featured, type: Boolean, default: false

  index(_type: 1)
  index(state: 1)
  index(active: 1)
  index(featured: 1)
  index(twitter_id: 1)
  index(additional_twitter_ids: 1)
  index(chamber: 1) # only applicable to legislators

  scope :active, where(active: true).asc(:chamber, :family_name) # no index includes `last_name`
  scope :featured, where(featured: true)

  delegate :signature_threshold, :biography, :links, to: :person_detail

  # only one featured person at a time
  after_save :make_all_others_unfeatured, if: :featured?

  # expensive, do this only when constrained by connected_to or the like
  def self.some_name_matches(name_fragment)
    any_of({ full_name: name_fragment },
           { first_name: name_fragment },
           { last_name: name_fragment },
           { full_name: /#{name_fragment}/i },
           { first_name: /#{name_fragment}/i },
           { last_name: /#{name_fragment}/i })
  end

  def self.only_types(types)
    where("_type" => { "$in" => types })
  end

  # non-chainable
  def self.criteria_for_types_for_location(location)
    location = LocationFormatter.new(location).format
    return where(id: nil) if location.nil?

    criteria = distinct("_type").collect do |type|
      type = "Person" if type.blank?
      type.constantize.for_location(location)
    end
  end

  def self.for_location(location, api = nil)
    if self.name != "Person"
      raise "this class needs a real implementation of for_location"
    end

    # plain Person cannot be relied on to have location data
    where('false')
  end

  # non-chainable
  def self.results_for_location(location)
    if self.name != "Person"
      raise "should not be called from subclass"
    end

    criteria_for_types_for_location(location).inject([]) do |results, criterium|
      results += criterium
    end
  end

  def self.default_api
    OpenStatesLegislatorService
  end

  # for now, only run if we have a clean slate
  def self.load_from_apis_for_jurisdiction(abbreviation, api = nil, adapter = nil)
    return if self.connected_to(abbreviation).count > 0

    api ||= default_api.new
    api.parsed_results_for_jurisdiction(abbreviation).map do |attributes|
      new.load_from_apis!(attributes, adapter: adapter)
    end
  end

  # @todo needs spec
  def load_from_apis!(attributes, options = {})
    adapt(attributes, options).save!
    PersonDetailRetriever.new(self, options).retrieve!
    self
  end

  # Inactive legislators will not have top-level `chamber` or `district` fields.
  #
  # @param [String,Symbol] `:chamber` or `:district`
  # @return [String,nil] the chamber, the district, or nil
  def most_recent(attribute)
    if read_attribute(attribute)
      read_attribute(attribute)
    else
      read_attribute(:old_roles).to_a.reverse.each do |_, roles|
        if roles
          roles.each do |role|
            return role[attribute.to_s] if role[attribute.to_s]
          end
        end
      end
      nil # don't return the enumerator
    end
  end

  # What political role does the person currently play?
  # Can be elected or something other like "adviser" or "spokesperson", etc.
  #
  # Expected to be fully meaningful in combination with class and perhaps
  # metadatum (e.g name of chamber for StateLegislator like "upper").
  #
  # Subclasses may populate with a dedicated field or dynamically based on
  # another value.
  #
  # Meant for programmatic use, all lower case.
  #
  # @return [String, nil]
  def political_position
    read_attribute(:political_position)
  end

  # Meant as common formal presentation of political position.
  #
  # Yeah, I know, it's presentation concern, but may be dynamically generated
  # in subclasses based on relation with metadatum and its own class.
  #
  # @return [String, nil]
  def political_position_title
    political_position ? political_position.humanize : nil
  end

  # Returns fields that are not available in Billy.
  #
  # @return [PersonDetail] the person's additional fields
  # @note `has_one` associations require a matching `belongs_to`, as they must
  #   be able to call `inverse_of_field`.
  def person_detail
    PersonDetail.where(person_id: id).first || PersonDetail.new(person: self)
  end

  # Returns the person's special interest group ratings.
  def ratings
    Rating.where(candidateId: votesmart_id || person_detail.votesmart_id)
  end

  # Returns questions answered by the person.
  def questions_answered
    questions.where(answered: true)
  end

  # Returns the person's sponsored bills.
  def bills
    Bill.where('sponsors.leg_id' => id)
  end

  # Returns the person's votes.
  def votes
    Vote.or({'yes_votes.leg_id' => id},
            {'no_votes.leg_id' => id},
            {'other_votes.leg_id' => id}) # no index
  end

  # Returns the person's committees.
  def committees
    roles = read_attribute(:roles)
    return Committee.where(id: []) unless roles

    ids = roles.map { |x| x['committee_id'] }.compact
    return Committee.in(id: []) unless ids.any?

    Committee.in(id: ids)
  end

  def verified?
    identities.where(status: 'verified').count > 0
  end

  def votesmart_id
    read_attribute(:votesmart_id)
  end

  def votesmart_biography_url
    votesmart_url('biography')
  end

  def votesmart_evaluations_url
    votesmart_url('evaluations')
  end

  def votesmart_key_votes_url
    votesmart_url('key-votes')
  end

  def votesmart_public_statements_url
    votesmart_url('public-statements')
  end

  def votesmart_campaign_finance_url
    votesmart_url('campaign-finance')
  end

  # so subclasses use standard _person partial
  # unless otherwise specified
  def to_partial_path
    "people/person"
  end

  def archive_photo_url
    old_photo_urls = Array(old_photo_urls)
    old_photo_urls << photo_url
    self.old_photo_urls = old_photo_urls
    self.photo_url = nil
    save!
  end

  private
  def votesmart_url(section = nil)
    if votesmart_id
      url = "http://votesmart.org/candidate/"
      url += "#{section}/" if section
      url += votesmart_id
    end
  end

  def adapt(attributes, options = {})
    adapter = options[:adapter]
    if adapter
      adapter.run(attributes)
    else
      self.attributes = attributes
    end

    # id cannot be mass assigned..., have to set it explictly
    # id = attributes['id']
    self
  end

  def make_all_others_unfeatured
    # specify superclass to get all people in subclasses
    Person.featured.nin(id: [id]).each do |record|
      record.update_attributes(featured: false)
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :force_http

  inherit_resources
  belongs_to :jurisdiction, parent_class: Metadatum, finder: :find_by_abbreviation, param: :jurisdiction
  respond_to :html
  respond_to :js, only: [:show, :bills, :committees, :votes, :ratings]
  actions :index, :show, :update
  custom_actions resource: [:bills, :committees, :votes, :ratings]

  before_filter :set_is_unaffiliated, only: [:index, :show]
  before_filter :redirect_to_unaffiliated_route_if_necessary, only: [:index, :show]

  before_filter :authenticate_user!, only: :update
  before_filter :check_can_manage_person, only: :update

  def show
    @blurb = Blurb.active.where(target_url: person_path(parent, resource)).first
    @questions = resource.questions.in(needs_confirmation: [nil, false])
                 .includes(:user).desc(:created_at).page(params[:page])
    tab "questions"

  rescue Mongoid::Errors::DocumentNotFound => error
    person_different_jurisdiction = Person.where(id: params[:id]).first

    if person_different_jurisdiction
      correct_jurisdiction = person_different_jurisdiction.state
      if correct_jurisdiction == Metadatum::Unaffiliated::ABBREVIATION
        redirect_to unaffiliated_person_path(params[:id], share: params[:share])
      else
        redirect_to person_path(correct_jurisdiction, params[:id], share: params[:share])
      end
    else
      raise error
    end
  end

  def bills
    # @bills = resource.bills.recent.includes(:questions).page(params[:page]) # no index includes `session`, so we omit it
    # if we allow questions on bills again, reinstate includes
    @bills = resource.bills.recent.page(params[:page]).per(10) # no index includes `session`, so we omit it
    tab "bills"
  end

  def committees
    # committees trigger a lot of subqueries, only do 5 per page
    @committees = resource.committees.page(params[:page]).per(5)
    tab "committees"
  end

  def votes
    @votes = resource.votes.page(params[:page])
    tab "votes"
  end

  def ratings
    @ratings = resource.ratings.page(params[:page])
    tab "ratings"
  end

  def update
    @person = Person.find(params[:id])
    params[:person] = params[@person.class.name.tableize.singularize.to_sym]
    update!(notice: "Person updated") do |format|
      format.html { redirect_to person_path(@person.state, @person) }
    end
  end

  private
  # @todo DRY with pages controller and improve
  # putting off, because it will likely be totally replaced
  def types
    @types ||= if params[:gov]
                @gov = params[:gov]
                 case @gov
                 when "state"
                   ["StateLegislator"]
                 when "federal"
                   ["FederalLegislator"]
                 end
               elsif @is_unaffiliated
                 ["Person"]
               else
                 if @jurisdiction && @jurisdiction.abbreviation.include?("-")
                   ["Councilmember"]
                 else
                   ["FederalLegislator"]
                 end
               end
  end

  def tab(tab)
    @tab = tab
    show! do |format|
      format.html { render action: "show" }
      format.js { render partial: @tab }
    end
  end

  def end_of_association_chain
    Person.connected_to(parent.abbreviation)
  end

  def collection
    # downcase covers api legacy set "person" for _type
    # @todo evaluate if in for type is too slow
    @people ||= begin
                  people = end_of_association_chain.includes(:questions, :identities)
                  unless @is_unaffiliated
                    people = people.active
                  end
                  people.only_types(types)
                end
  end

  def set_is_unaffiliated
    @is_unaffiliated = params[:jurisdiction] ==
      Metadatum::Unaffiliated::ABBREVIATION
  end

  def redirect_to_unaffiliated_route_if_necessary
    if request.fullpath.include?(Metadatum::Unaffiliated::ABBREVIATION)
      path = if params[:action] == "index"
               unaffiliated_people_path
             else
               unaffiliated_person_path(params[:id])
             end
      redirect_to path
    end
  end

  def check_can_manage_person
    unless current_user.can?(:manage_person)
      raise Authority::SecurityViolation.new(current_user,
                                             :manage_person,
                                             PeopleController)
    end
  end
end

app/views/people/_bills.html.erb
<section class="related_focus">
  <ol class="bills">
    <%= render @bills %>
  </ol>

  <%= paginate @bills, outer_window: 1, params: {format: nil}, replace: '.related_focus', scroll: '.related_wrap' %>
</section>

app/views/people/_committees.html.erb
<section class="related_focus">
  <ol class="bills">
    <%= render @committees %>
  </ol>

  <%= paginate @committees, outer_window: 1, params: { format: nil }, replace: ".related_focus", scroll: '.related_wrap' %>
</section>

app/views/people/_featured.html.erb
<div class="featured">
  <div class="emph">
    <div class="avatar">
      <% if featured.image? %>
        <%= cdn_image_tag(featured.image, state: featured.state, size: "60x60", alt: "") %>
      <% else %>
        <%= image_tag("placeholder.png", size: "60x60", alt: "") %>
      <% end %>
    </div>
    <div class="featured-headline">
      <%= link_to featured.name, person_path(featured["state"], featured) %>&nbsp;&nbsp;<% if featured.verified? -%><i class="icon-ok-sign is-verified"><span class="verified-tooltip">AskThem Verified</span></i><% end -%>
      <span class="jurisdiction"><%= person_attributes(featured) %></span>
    </div>
    <div class="featured-body">
      <span class="stats">
        <%- if featured.questions.count > 0 %>
          <span><%= pluralize featured.questions.count, "Question" %></span>
          <%- if featured.questions_answered.count > 0 %>
            <span><%= link_to(pluralize(featured.questions_answered.count, "Answer"), have_answers_questions_path(featured.state, person: featured)) -%></span>
          <%- end %>
        <%- else %>
          <%= link_to "Ask the first question >>", new_question_path(featured.state, person: featured) -%>
        <%- end %>
      </span>
    </div>
  </div>
</div>

app/views/people/_person.html.erb
<% with_button = @only_show && @only_show == "people" %>

<li>
  <div class="avatar">
    <% if person.image? %>
      <%= cdn_image_tag(person.image, state: person.state, size: "60x60", alt: "") %>
    <% else %>
      <%= image_tag("placeholder.png", size: "60x60", alt: "") %>
    <% end %>
  </div>
  <div class="person-info">
    <h2><%= link_to person.name, person_path(person["state"], person) %>&nbsp;&nbsp;<% if person.verified? -%><i class="icon-ok-sign is-verified"><span class="verified-tooltip">AskThem Verified</span></i><% end -%></h2>
    <span class="jurisdiction"><%= person_attributes(person) %></span>
    <span class="stats">
      <%- if person.questions.count > 0 %>
        <span><%= pluralize person.questions.count, "Question" %></span>
        <%- if person.questions_answered.count > 0 %>
          <span><%= link_to(pluralize(person.questions_answered.count, "Answer"), have_answers_questions_path(person.state, person: person)) -%></span>
        <%- end %>
      <%- elsif with_button == false %>
        <%= link_to "Ask the first question >>", new_question_path(person.state, person: person) -%>
      <%- end %>
    </span>
    <%- if with_button %>
      <%= link_to "Ask question", new_question_path(person.state, person: person), class: "cta-pill person-list-button" -%>
    <%- end %>
  </div>
</li>

app/views/people/_questions.html.erb
<section class="questions related_focus">
  <% if @questions.any? %>
  <ol>
    <%= render @questions %>
  </ol>
  <% else %>
  <div class="notif info">
    <h3>Nobody has asked any questions yet!</h3>
    <p>Do you want to get the ball rolling?</p>
    <%= link_to "Ask this person a Question", new_question_path(@jurisdiction.abbreviation, person: @person), class: "cta-pill" %>
  </div>
  <% end %>

  <%= paginate @questions, outer_window: 1, params: { format: nil }, replace: ".related_focus", scroll: '.related_wrap' %>
</section>

app/views/people/_ratings.html.erb
<section class="related_focus">
  <ol>
    <%= render @ratings %>
  </ol>
  <%= paginate @ratings, outer_window: 1, params: { format: nil }, replace: ".related_focus", scroll: '.related_wrap' %>
</section>

app/views/people/_votes.html.erb
<section class="related_focus">
  <ol>
    <%= render @votes %>
  </ol>

  <%= paginate @votes, outer_window: 1, params: {format: nil}, replace: '.related_focus', scroll: '.related_wrap' %>
</section>

app/views/people/index.html.erb
<%= render 'shared/navigation' unless @is_unaffiliated %>

<section class="people listings unaffiliated-people">
  <%- unless @is_unaffiliated %>
    <div class="filters">
      <span class="info">Filter by:</span><%# @todo DM are these really the filters we're using? %>
      <ul class="menu">
        <li class="selected">District <span class="icon-angle-down"></span></li>
        <li class="menu">
          <ul>
            <li><%= link_to 'Option', '#' %> <span class="icon-angle-down"></span></li>
            <li><%= link_to 'Option', '#' %> <span class="icon-angle-down"></span></li>
            <li><%= link_to 'Option', '#' %> <span class="icon-angle-down"></span></li>
            <li><%= link_to 'Option', '#' %> <span class="icon-angle-down"></span></li>
          </ul>
        </li>
      </ul>
      <ul class="menu">
        <li class="selected">Official <span class="icon-angle-down"></span></li>
        <li class="menu">
          <ul>
            <li><%= link_to 'Option', '#' %> <span class="icon-angle-down"></span></li>
            <li><%= link_to 'Option', '#' %> <span class="icon-angle-down"></span></li>
            <li><%= link_to 'Option', '#' %> <span class="icon-angle-down"></span></li>
            <li><%= link_to 'Option', '#' %> <span class="icon-angle-down"></span></li>
          </ul>
        </li>
      </ul>
      <div class="search"><%# @todo DM full-text search within state? %>
        <input type="text" name="" id="" placeholder="Search state">
        <input type="submit" value="">
      </div>
    </div>
  <%- end %>

  <ol class="people-list">
    <%= render @people %>
  </ol>
</section>

app/views/people/show.html.erb
<%- if @is_unaffiliated %>
  <p>&nbsp;</p>
<%- else %>
  <%= render 'shared/navigation' %>
<%- end %>

<section class="people">
  <header>
    <%= render @blurb if @blurb %>

    <div class="person_info">
      <% if @person.image? %>
        <div class="avatar">
          <%= cdn_image_tag(@person.image, state: @person.state, size: '80x80', alt: '', class: 'person_photo') %>
        </div>
      <% else %>
        <%= image_tag('placeholder.png', size: '80x80', alt: '') %>
      <% end %>

      <div class="person_details">
        <h1>
          <%= @person.name %>
        </h1>
        <h2><%= person_attributes(@person) %></h2>
        <% if @person.verified? -%>
          <i class='icon-ok-sign is-verified'><span> AskThem Verified</span></i>
        <% end -%>
        <div class="attr">
          <span class="count"><%= pluralize @person.questions.count, 'question' %></span>
          <%- if @person.questions_answered.count > 0 %>
            <span class="count"><%= link_to(pluralize(@person.questions_answered.count, "answer"), have_answers_questions_path(@person.state, person: @person)) -%></span>
          <%- end %>
        </div>
      </div>

      <% if @person.person_detail.biography? %>
        <p class="person_wikipedia"><%= truncate(@person.person_detail.biography, length: 130) %> <%= link_to 'Read more on Wikipedia', @person.person_detail.links.find_by(note: 'Wikipedia').url %></p>
      <% end %>
    </div>
    <%= link_to 'Ask this person a Question', new_question_path(@jurisdiction.abbreviation, person: @person), class: 'cta-pill' %>
  </header>

  <div class="related_wrap">
    <div class="related_data">
      <nav>
        <ul class="related_nav">
          <li><%= link_to 'Questions', person_path(@jurisdiction.abbreviation, @person.id), tab_options('questions', 'show') %></li>
          <%- if @person.is_a? StateLegislator %>
            <li><%= link_to 'Sponsored Bills', bills_person_path(@jurisdiction.abbreviation, @person.id), tab_options('bills') %></li>
            <li><%= link_to 'Votes', votes_person_path(@jurisdiction.abbreviation, @person.id), tab_options('votes') %></li>
            <li><%= link_to 'Committees', committees_person_path(@jurisdiction.abbreviation, @person.id), tab_options('committees') %></li>
          <% end %>
          <%- unless @person.state == Metadatum::Unaffiliated::ABBREVIATION %>
            <li><%= link_to 'Interest Groups', ratings_person_path(@jurisdiction.abbreviation, @person.id), tab_options('ratings') %></li>
          <%- end %>
        </ul>
      </nav>

      <div class="related_content">
        <%= render partial: @tab %>
        <aside>
          <%- if staff_member? -%>
            <div class="question-controls">
              <h4>Staff Actions:</h4>
              <ul>
                <li>
                  <%- unless @person.featured? %>
                    <%= form_for @person,
                      url: person_path(@jurisdiction, @person),
                      html: { style: "inline" } do |f| -%>
                      <%= f.hidden_field :featured, value: true -%>
                      <%= f.submit "Make Featured", class: "cta-pill" %>
                    <%- end %>
                  <%- end %>
                </li>
                <li>
                  <%= link_to "Add blurb",
                  new_blurb_path(target_url: person_path(@jurisdiction, @person)),
                  class: "cta-pill" %>
                </li>
              </ul>
            </div>
          <%- end %>

          <% if @person.email? %>
            <section>
              <h4>Email:</h4><p><%= mail_to @person.email %></p>
            </section>
          <% end %>

          <% if @person.twitter_id.present? %>
            <section>
              <h4>Twitter:</h4>
              <p>
                <%= link_to "@#{@person.twitter_id}", "//twitter.com/#{@person.twitter_id}" -%>
              </p>
            </section>
          <% end %>

          <% if @person['offices'] -%>
            <% @person['offices'].each do |office| %>
              <section>
                <% if office['type'] %>
                  <h4>
                    <%=t office['type'], scope: [:offices, :types], default: office['type'] %>
                  </h4>
                <% end %>
                <ul>
                  <% if office['phone'] && office['address'].is_a?(String) %>
                    <li>Tel: <%= office['phone'] %></li>
                  <% end %>
                  <% if office['fax'] && office['address'].is_a?(String) %>
                    <li>Fax: <%= office['fax'] %></li>
                  <% end %>
                  <% if office['address'] && office['address'].is_a?(String) %>
                    <li><%= simple_format office['address'] %></li>
                  <% end %>
                </ul>
              </section>
            <% end %>
          <% end %>
        </aside>
      </div>
    </div>
  </div>
</section>