config/routes.rb
OpenGovernment::Application.routes.draw do
  resources :blurbs

  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'sessions'
  }

  if ENV["SPLASH_AS_HOMEPAGE"]
    root to: 'pages#splash'
    get 'home' => 'pages#index'
  else
    root to: 'pages#index'
  end

  # generate a custom robots.txt
  get 'robots.:format' => 'robots#show'

  get 'widgets/builder' => 'pages#widget_builder'
  get 'splash' => 'pages#splash'
  get 'electeds' => 'pages#splash'
  get 'elected_signup' => 'pages#elected_signup'
  get 'about', to: 'pages#about'
  get 'support', to: 'pages#support'
  get 'faq', to: 'pages#faq'
  get 'honestads', to: 'pages#honestads'
  get 'map', to: 'pages#map'
  get 'terms-of-service', to: 'pages#terms_of_service'
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'candidates', to: 'pages#candidates', as: :candidates_page

  resources :users, only: [:show, :update] do
    member do
      get 'signatures'
    end
  end
  resources :signatures, only: :create
  resources :answers, only: [:create, :edit, :update]

  resources :identities, only: :update

  scope ':jurisdiction' do
    resources :bills, only: [:index, :show] do
      member do
        get 'sponsors'
      end
    end

    resources :people, only: [:index, :show, :update] do
      member do
        get 'bills'
        get 'committees'
        get 'votes'
        get 'ratings'
      end
    end

    resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'preview'
        get 'need_signatures'
        get 'have_answers'
        get 'need_answers'
        get 'recent'
      end

      resources :signatures, only: :index
    end

    resources :subjects, only: [:index, :show]

    match 'overview/lower' => 'pages#lower', as: :lower_overview, via: :get
    match 'overview/upper' => 'pages#upper', as: :upper_overview, via: :get
    match 'overview/bills' => 'pages#bills', as: :bills_overview, via: :get
    match 'overview/meetings' => 'pages#meetings', as: :meetings_overview, via: :get
    match 'overview/votes' => 'pages#key_votes', as: :key_votes_overview, via: :get

    get 'map', to: 'pages#map'

    resources :candidates
  end

  match 'email_upkeep' => 'email_upkeep#index', as: :email_upkeep, via: [:post]

  match 'locator' => 'pages#locator', as: :locator, via: [:get, :post]
  match 'identifier' => 'pages#identifier', as: :identifier, via: :get
  match 'contact_info' => 'pages#contact_info', as: :contact_info, via: :get
  match 'channel' => 'pages#channel', as: :channel, via: :get
  match 'people' => 'people#index', as: :unaffiliated_people, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'people/:id' => 'people#show', as: :unaffiliated_person, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'questions' => 'questions#index', as: :unaffiliated_questions, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'questions/:id' => 'questions#show', as: :unaffiliated_question, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match ':jurisdiction' => 'pages#overview', as: :jurisdiction, via: :get
end

app/views/shared/_accept_terms.html.erb
<div class="sidebar-text">
  By <%= verb -%>, you accept AskThem's
  <a href="/terms-of-service">terms of use</a> and
  <a href="/privacy-policy">privacy policy</a>
  <%- if @question && @question.user.partner? %>
    and may receive updates from <%= link_to @question.user.given_name, user_path(@question.user) -%>
  <%- end %>
</div>

app/views/shared/_banner.html.erb
<%- if ENV["BANNER_HTML"].present? && session[:banner_viewed].blank? -%>
  <div class="banner">
    <div class="banner-content">
      <a href="#" class="banner-close"><i class="icon-remove"></i></a>
      <div class="banner-header">
        <%= raw(ENV["BANNER_HTML"]) %>
      </div>
    </div>
  </div>
  <% session[:banner_viewed] = true %>
<%- end %>

app/views/shared/_chartbeat.html.erb
<% if Rails.env.production? && ENV["CHARTBEAT_HOSTNAME"].present? -%>
<script type="text/javascript">
  var _sf_async_config = { uid: <%= ENV["CHARTBEAT_UID"] -%>, domain: '<%= ENV["CHARTBEAT_HOSTNAME"] -%>', useCanonical: true };
  (function() {
    function loadChartbeat() {
      window._sf_endpt = (new Date()).getTime();
      var e = document.createElement('script');
      e.setAttribute('language', 'javascript');
      e.setAttribute('type', 'text/javascript');
      e.setAttribute('src','//static.chartbeat.com/js/chartbeat.js');
      document.body.appendChild(e);
    };
    var oldonload = window.onload;
    window.onload = (typeof window.onload != 'function') ?
      loadChartbeat : function() { oldonload(); loadChartbeat(); };
  })();
</script>
<% end -%>

app/views/shared/_facebook_connect.html.erb
<%- if ENV["FACEBOOK_APP_ID"].present? -%>
  <script>
   window.fbAsyncInit = function () {
     FB.init({
       appId: '<%= ENV["FACEBOOK_APP_ID"] -%>',
       status: true,
       cookie: true,
       logging: false,
       xfbml: true,
       channelUrl: '<%= channel_url %>'
     });
   };
   (function(d, s, id) {
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) return;
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js"; // adding parameters calls FB.init
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
  </script>
<%- end %>

app/views/shared/_google_analytics.html.erb
<% if Rails.env.production? && ENV["GOOGLE_ANALYTICS_APP_ID"].present? -%>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV["GOOGLE_ANALYTICS_APP_ID"] -%>', '<%= ENV["GOOGLE_ANALYTICS_HOSTNAME"] -%>');
  ga('send', 'pageview');

</script>
<% end -%>

app/views/shared/_navigation.html.erb
<section>
  <nav>
    <ul class="level">
      <li<%= raw(' class="active"') if federal? %>>
        <%= link_to federal_path do %>
          <%= state_name %> Federal
        <% end %>
        <i class="icon-angle-down"></i>
      </li>
      <li<%= raw(' class="active"') if state? %>>
        <%= link_to state_path do %>
          <%= state_name %> State
        <% end %>
        <i class="icon-angle-down"></i>
      </li>
      <%- if local_jurisdiction %>
        <li <%= @jurisdiction.abbreviation == local_jurisdiction.abbreviation ? raw(' class="active"') : '' %> >
          <%= link_to jurisdiction_path(jurisdiction: local_jurisdiction.abbreviation) do %>
            <%= local_jurisdiction.name %>
          <% end %>
          <%- if local_jurisdictions.count > 1 %>
            <span class="jurisdiction-change"><a href="#" class="navigation-modal-open">change</a></span>
            <%- counties = local_jurisdictions.select { |lj| lj.id.include?("-county") } %>
            <%- cities = local_jurisdictions - counties - [local_jurisdiction] %>
            <div class="navigation-overlay" style="display:none;"></div>
            <div class="navigation-modal" style="display:none;">
              <div class="modal-content">
                <a href='#' class="modal-close"><i class="icon-remove"></i></a>
                <h2 class="modal-header">
                  Choose a different place
                </h2>
                <div class="modal-copy-wrap">
                  <%- if cities.any? %>
                    <ul>
                      <%- cities.each do |city| %>
                        <li><%= link_to city.name, jurisdiction_path(jurisdiction: city.abbreviation) -%></li>
                      <%- end %>
                    </ul>
                  <%- end %>

                  <%- if counties.any? %>
                    <ul>
                      <%- counties.each do |county| %>
                        <li><%= link_to county.name, jurisdiction_path(jurisdiction: county.abbreviation) -%></li>
                      <%- end %>
                    </ul>
                  <%- end %>
                </div>
              </div>
              <%= image_tag("mark.svg", class: "modal-logo") %>
            </div>
          <%- end %>
          <i class="icon-angle-down"></i>
        </li>
      <% end %>
    </ul>
    <% unless (params[:controller] == 'questions' && params[:action] == 'show') %>
      <ul class="top_nav">
        <li><a name="top" style="display:none;"></a><%= tab 'Questions', @gov ? questions_path(gov: @gov) : questions_path %></li>
        <% unless 1 # federal? -%>
          <li><%= tab 'Bills', bills_path %></li>
        <% end %>
        <%# @todo extract to helper -%>
        <% unless 1 %>
          <li><%= tab 'People', @gov ? people_path(gov: @gov) : people_path %></li>
          <% if @jurisdiction.subjects? %>
          <li><%= tab 'Issues', subjects_path %></li>
          <% end %>
        <% end %>
        <%# <li><%= tab 'Money', '#' </li> @todo %>
          <li><%= tab 'Government', jurisdiction_path %></li>
        <% if should_have_ask_question_in_header? -%>
          <%= link_to 'Ask a Question', new_question_path(@jurisdiction.abbreviation), class: 'cta-pill top-nav-ask' %>
        <% end %>
        </ul>
    <% end %>
  </nav>
</section>

app/views/shared/_no_questions.html.erb
<div class="first-question-in-area">
  <h3>Ask one of the first questions in your area!</h3>
  <%= generic_ask_question "Ask your own Question",  class: "cta-pill" %>
</div>

app/views/shared/_optimizely.html.erb
<%- if Rails.env.production? && ENV["OPTIMIZELY_FILENAME"].present? -%>
  <script src="//cdn.optimizely.com/js/<%= ENV["OPTIMIZELY_FILENAME"] -%>.js"></script>
<%- end  %>

app/views/shared/_partner_return_to.html.erb
<%- info = session[:referring_partner_info] %>
<%- if info && info[:name].present? %>
  <%- target_url = info[:return_url] || info[:url] %>
  <%- link_content = info[:name] %>
  <%- if info[:logo] %>
    <%- link_content = raw("<img src=\"#{info[:logo]}\" class=\"partner-logo\" alt=\"#{info[:name]}\">") %>
  <%- end %>

  <div class="partner-return-to">
    <div class="partner-intro">return to</div> <%= raw("<a href=\"#{target_url}\">#{link_content}</a>") -%>
  </div>
<%- end %>

app/views/shared/_question_progress.html.erb
<div class="progress">
  <div class="actions scroll_this">
    <h4>Your Question</h4>
    <div class="row">
      <div class="question_progress">
        <div class="progress_filler" style="width: 0%;"> </div>
      </div>
      <span class="question_progress_count">
        <strong>0</strong> out of <strong>500</strong> Signatures
      </span>
    </div>  
    <div class="row">
      <ul class="recipient">
        <li>
          <div class="avatar">
            <img src="http://lorempixel.com/130/130/" alt="" />
          </div>
          <div class="person-info">
            <h2>Ron Paul</h2>
            <span class="jurisdiction">R. - 6th House District</span>
          </div>
        </li>
      </ul>
    </div>
    <div class="row">
      <div class="question_preview">
        <!--
          If nothing:
        -->
        <h5 class="empty">Nothing yet&hellip;</h5>
      
        <!--
          When content is added:
        -->
        <h5>Why is the sky blue?</h5>
        <p>Pandas typically eat bamboo because it is delicious and good for them. By eating...</p>
      </div>
    </div>
    <!--
      If issue is selected, otherwise add "last" class to .row above
    -->
    <div class="row last">
      <div class="question_issue">
        <span>Issue: <strong>Education</strong></span>
      </div>
    </div>
    <a href="#" class="cta_pill">Next <span class="icon-caret-right"></span></a>
    <span class="count">1 of 3</span>
  </div>
</div>

app/views/shared/_user.html.erb
<% if user_signed_in? %>
<li><%= link_to "My Questions", user_path(current_user) %></li>
<li><%= link_to "Settings", edit_user_registration_path %></li>
<li><%= link_to "Sign out", destroy_user_session_path %></li>
<% if false %>
  <li>
    <%= link_to "#" do %><%# @todo ST make dropdown appear %>
      <%= current_user.alternate_name %> <span class="icon-angle-down"></span>
    <% end %>
  </li>
<% end %>
<% else %>
<li><%= link_to "Sign up", new_user_registration_path %></li>
<li><%= link_to "Login", new_user_session_path %></li>
<li><%= link_to("Login with Facebook",
                user_omniauth_authorize_url(:facebook,
                protocol: Rails.env.production? ? "https://" : "http://"),
                class: "facebook-login") -%></li>
<% end %>