config/routes.rb
OpenGovernment::Application.routes.draw do
  resources :blurbs

  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'sessions'
  }

  if ENV["SPLASH_AS_HOMEPAGE"]
    root to: 'pages#splash'
    get 'home' => 'pages#index'
  else
    root to: 'pages#index'
  end

  # generate a custom robots.txt
  get 'robots.:format' => 'robots#show'

  get 'widgets/builder' => 'pages#widget_builder'
  get 'splash' => 'pages#splash'
  get 'electeds' => 'pages#splash'
  get 'elected_signup' => 'pages#elected_signup'
  get 'about', to: 'pages#about'
  get 'support', to: 'pages#support'
  get 'faq', to: 'pages#faq'
  get 'honestads', to: 'pages#honestads'
  get 'map', to: 'pages#map'
  get 'terms-of-service', to: 'pages#terms_of_service'
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'candidates', to: 'pages#candidates', as: :candidates_page

  resources :users, only: [:show, :update] do
    member do
      get 'signatures'
    end
  end
  resources :signatures, only: :create
  resources :answers, only: [:create, :edit, :update]

  resources :identities, only: :update

  scope ':jurisdiction' do
    resources :bills, only: [:index, :show] do
      member do
        get 'sponsors'
      end
    end

    resources :people, only: [:index, :show, :update] do
      member do
        get 'bills'
        get 'committees'
        get 'votes'
        get 'ratings'
      end
    end

    resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'preview'
        get 'need_signatures'
        get 'have_answers'
        get 'need_answers'
        get 'recent'
      end

      resources :signatures, only: :index
    end

    resources :subjects, only: [:index, :show]

    match 'overview/lower' => 'pages#lower', as: :lower_overview, via: :get
    match 'overview/upper' => 'pages#upper', as: :upper_overview, via: :get
    match 'overview/bills' => 'pages#bills', as: :bills_overview, via: :get
    match 'overview/meetings' => 'pages#meetings', as: :meetings_overview, via: :get
    match 'overview/votes' => 'pages#key_votes', as: :key_votes_overview, via: :get

    get 'map', to: 'pages#map'

    resources :candidates
  end

  match 'email_upkeep' => 'email_upkeep#index', as: :email_upkeep, via: [:post]

  match 'locator' => 'pages#locator', as: :locator, via: [:get, :post]
  match 'identifier' => 'pages#identifier', as: :identifier, via: :get
  match 'contact_info' => 'pages#contact_info', as: :contact_info, via: :get
  match 'channel' => 'pages#channel', as: :channel, via: :get
  match 'people' => 'people#index', as: :unaffiliated_people, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'people/:id' => 'people#show', as: :unaffiliated_person, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'questions' => 'questions#index', as: :unaffiliated_questions, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'questions/:id' => 'questions#show', as: :unaffiliated_question, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match ':jurisdiction' => 'pages#overview', as: :jurisdiction, via: :get
end

app/models/bill.rb
require 'ostruct'

# Billy
class Bill
  include Mongoid::Document

  # The bill's jurisdiction.
  belongs_to :metadatum, foreign_key: 'state'
  # The bill's votes.
  has_many :votes
  # Questions about the bill.
  has_many :questions

  field :subjects, type: Array # for FactoryGirl

  scope :recent, includes(:metadatum).desc('action_dates.last')
  scope :in_session, ->(session) {recent.where(session: session)}

  DATE_ORDER = {
    'lower' => [
      'first',
      'passed_lower',
      'passed_upper',
      'signed',
      'last',
    ],
    'upper' => [
      'first',
      'passed_upper',
      'passed_lower',
      'signed',
      'last',
    ]
  }

  OTHER_CHAMBER = {
    'lower' => 'upper',
    'upper' => 'lower',
  }

  index(state: 1)
  index(chamber: 1)
  index("sponsors.leg_id" => 1)
  index("action_dates.last" => 1)

  # Returns fields that are not available in Billy.
  #
  # @return [BillDetail] the bill's additional fields
  # @note `has_one` associations require a matching `belongs_to`, as they must
  #   be able to call `inverse_of_field`.
  def bill_detail
    BillDetail.where(bill_id: id).first || BillDetail.new(bill: self)
  end

  # Returns answered questions about the bill.
  def questions_answered
    questions.where(answered: true)
  end

  # @return [String] the bill's human-readable session
  def session_label
    metadatum['session_details'][read_attribute(:session)]['display_name']
  end

  # @return [Array] the major actions sorted by date
  def dates
    @dates ||= begin
      dates = read_attribute(:action_dates).to_a

      # Remove extra chambers.
      chamber = read_attribute(:chamber)
      if metadatum['chambers'].size == 1
        dates.delete_at(dates.index{|action,_| action.include?(OTHER_CHAMBER[chamber])})
      end

      # Sort the dates appropriately.
      order = DATE_ORDER[chamber]
      dates.sort do |(a,_),(b,_)|
        order.index(a) <=> order.index(b)
      end
    end
  end

  # Returns the sponsors of the bill.
  #
  # @param [Hash] opts optional arguments
  # @option opts [Integer] :limit the number of sponsors to return
  # @option opts [Symbol] :only the type of sponsors to return
  # @return [Array] the people and committees sponsoring the bill
  # @note We do this because the OpenStates database is inconsistent.
  def people_and_committee_sponsors(opts = {})
    sponsors = read_attribute(:sponsors)
    case opts[:only]
    when :people
      sponsors.select!{|x| x['leg_id']}
    when :committees
      sponsors.select!{|x| x['committee_id']}
    end
    sponsors = sponsors.first(opts[:limit]) if opts.key?(:limit)

    documents_by_id = {}

    # Get all the legislator sponsors in a single query.
    ids = sponsors.select{|x| x['leg_id']}.map{|x| x['leg_id']}
    unless ids.empty?
      criteria = Person.where(_id: {'$in' => ids})
      if opts[:eager]
        criteria = criteria.includes(:questions).includes(:identities)
      end
      criteria.each do |document|
        documents_by_id[document.id] = document
      end
    end

    # Get all the committee sponsors in a single query.
    ids = sponsors.select{|x| x['committee_id']}.map{|x| x['committee_id']}
    unless ids.empty?
      Committee.where(_id: {'$in' => ids}).each do |document|
        documents_by_id[document.id] = document
      end
    end

    # Maintain the sponsors' order. Not every bill has foreign keys for its
    # sponsors, e.g. WIB00000879.
    sponsors.map do |sponsor|
      document = documents_by_id[sponsor['leg_id'] || sponsor['committee_id']]
      if document
        document['type'] = sponsor['type']
      else
        document = OpenStruct.new(name: sponsor['name'], type: sponsor['type'], to_partial_path: 'unknown/unknown')
      end
      document
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_filter :force_http

  inherit_resources
  belongs_to :jurisdiction, parent_class: Metadatum, finder: :find_by_abbreviation, param: :jurisdiction
  respond_to :html
  respond_to :js, only: [:index, :show, :sponsors]
  actions :index, :show
  custom_actions resource: :sponsors

  def index
    index! do |format|
      format.js {render partial: 'page'}
    end
  end

  def show
    sponsors
    # questions aren't in use yet, default to sponsors for time being
    # @questions = resource.questions.page(params[:page])
    # tab 'questions'
  end

  def sponsors
    @sponsors = resource.people_and_committee_sponsors(eager: true)
    tab 'sponsors'
  end

private

  def tab(tab)
    @tab = tab
    show! do |format|
      format.html {render action: 'show'}
      format.js {render partial: @tab}
    end
  end

  def end_of_association_chain
    Bill.connected_to(parent.abbreviation)
  end

  def collection
    # @bills ||= end_of_association_chain.in_session(parent.current_session).includes(:questions).page(params[:page])
    @bills ||= end_of_association_chain
      .in_session(parent.current_session)
      .page(params[:page])
  end
end

app/views/bills/_bill.html.erb
<li>
  <div class="bill_content">
    <%= link_to bill['bill_id'], bill_path(@jurisdiction.abbreviation, bill), class: 'title' %>
    <p>
      <%= short_bill_title(bill) %>, <%= bill.session_label %>
    </p>
    <ol class="actions">
      <% bill.dates.select{ |_, date| date }.each do |action, date| %>
        <% date = Time.zone.parse(date) if date && date.is_a?(String) %>
        <% if action == 'first' %>
          <li<% if date %> class="active"<% end %>>
            Introduced
            <%= l(date, format: :bill) if date %>
          </li>
        <% elsif action == 'passed_lower' %>
          <li<% if date %> class="active"<% end %>>
            Passed <%= @jurisdiction.chamber_name('lower') %>
            <%= l(date, format: :bill) if date %>
          </li>
        <% elsif action == 'passed_upper' %>
          <li<% if date %> class="active"<% end %>>
            Passed <%= @jurisdiction.chamber_name('upper') %>
            <%= l(date, format: :bill) if date %>
          </li>
        <% elsif action == 'signed' %>
          <li<% if date %> class="active"<% end %>>
            Signed into Law
            <%= l(date, format: :bill) if date %>
          </li>
        <% end %>
      <% end %>
    </ol>
  </div>

  <ul class="activity">
    <!-- <li><%# pluralize bill.questions.count, 'question' %></li> -->
    <% bill.people_and_committee_sponsors(limit: 5, only: :people).each do |sponsor| %><%# @note N+1 query %>
      <li class="depiction">
        <% if Person === sponsor %>
          <% if sponsor.image? %>
            <%= link_to(cdn_image_tag(sponsor.image, size: '50x50', alt: sponsor.name), person_path(@jurisdiction.abbreviation, sponsor)) %>
          <% else %>
            <%= image_tag('placeholder.png', size: '50x50', alt: '') %>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="clear"></div>
</li>

app/views/bills/_page.html.erb
<div id="page">
  <ol class="bills">
    <%= render @bills %>
  </ol>

  <%= paginate @bills, outer_window: 1, params: {format: nil}, replace: '#page', scroll: 'section' %>
</div>

app/views/bills/_questions.html.erb
<section class="questions related_focus">
  <% if @questions.any? %>
  <ol>
    <%= render @questions %>
  </ol>
  <% else %>
  <div class="notif info">
    <!-- <h3>Nobody has asked any questions yet!</h3>
    <p>Do you want to get the ball rolling?</p>
    <%# link_to 'Ask about this Bill', new_question_path(@jurisdiction.abbreviation), class: 'cta-pill' %> -->
  </div>
  <% end %>
</section>

app/views/bills/_sponsors.html.erb
<section class="related_focus">
  <ol class="people-list">
    <%= render @sponsors %>
  </ol>
</section>

app/views/bills/index.html.erb
<%= render 'shared/navigation' %>

<section class="bills listings">
  <div class="filters">
    <span class="info">Filter by:</span><%# @todo DM are these really the filters we're using? %>
    <a href="#" class="radio_button filter inactive"><span class="use"></span>Date</a>

    <a href="#" class="radio_button filter inactive"><span class="use"></span>Recent Actions</a>

    <a href="#" class="radio_button filter inactive"><span class="use"></span>Most Viewed</a>

    <a href="#" class="radio_button filter inactive"><span class="use"></span>Key Votes</a>

    <div class="search"><%# @todo DM full-text search within state? %>
      <input type="text" name="" id="" placeholder="Search state">
      <input type="submit" value="">
    </div>
  </div>

  <%= render partial: 'page' %>
</section>

app/views/bills/show.html.erb
<%= render 'shared/navigation' %>

<section class="bills">
  <header>
    <div class="bill_info">
      <div class="bill_details">
        <h2>
          <strong><%= @bill['bill_id'] %></strong>
          <%= @bill.session_label %>
          <% if @bill['versions'].last %>
            <%= link_to 'Read the complete bill →', @bill['versions'].last['url'] %>
          <% end %>
        </h2>
        <h1 class="title_short">
          <%= short_bill_title(@bill) %>
          <% if @bill['title'].length >= 95 %>
            <a href="#" class="show_full_title" target="title"><span class="icon-plus"></span> Show full</a>
          <% end %>
        </h1>
        <% if @bill['title'].length >= 95 %>
          <p class="show_full title_long" style="display:none;">
            <%= @bill['title'] %>
            <a href="#" class="show_short_title" target="title"><span class="icon-minus"></span> Show less</a>
          </p>
        <% end %>
        <div class="attr">
          <span class="attr">
            <%= @jurisdiction.chamber_name(@bill['chamber']) %>
          </span>
          <span class="attr">
            <%= @bill.type.first.titleize %>
          </span>
          <!-- <span class="attr"><%# pluralize @bill.questions.count, 'question' %></span>
          <span class="attr"><%# pluralize @bill.questions_answered.count, 'answer' %></span> -->
        </div>
        <ol class="actions">
          <% @bill.dates.each do |action, date| %>
            <% date = Time.zone.parse(date.to_s) %>
            <% if action == 'first' %>
              <li<% if date %> class="active"<% end %> %>>
                Introduced
                <%= l(date, format: :bill) if date %>
                <span class="icon-circle-arrow-right"></span>
              </li>
            <% elsif action == 'passed_lower' %>
              <li<% if date %> class="active"<% end %>>
                Passed <%= @jurisdiction.chamber_name('lower') %>
                <%= l(date, format: :bill) if date %>
                <span class="icon-circle-arrow-right"></span>
              </li>
            <% elsif action == 'passed_upper' %>
              <li<% if date %> class="active"<% end %>>
                Passed <%= @jurisdiction.chamber_name('upper') %>
                <%= l(date, format: :bill) if date %>
                <span class="icon-circle-arrow-right"></span>
              </li>
            <% elsif action == 'signed' %>
              <li<% if date %> class="active"<% end %>>
                Signed into Law
                <%= l(date, format: :bill) if date %>
              </li>
            <% end %>
          <% end %>
        </ol>
      </div>
    </div>
    <!-- <%# link_to 'Ask about this Bill', new_question_path(@jurisdiction.abbreviation, bill: @bill), class: 'bill_detail cta-pill' %> -->
    <%# link_to 'Tell your Senator what you think', '#', class: 'sim_act' %>
  </header>

  <div class="related_wrap">
    <div class="related_data">
      <nav>
        <ul class="related_nav">
          <!-- <li><%# link_to 'Questions', bill_path(@jurisdiction.abbreviation, @bill.id), tab_options('questions', 'show') %></li> -->
          <li><%= link_to 'Sponsors', sponsors_bill_path(@jurisdiction.abbreviation, @bill.id), tab_options('sponsors') %></li>
        </ul>
      </nav>

      <div class="related_content">
        <%= render partial: @tab %>
        <aside>
          <% if @bill['sponsors'].present? && @tab != "sponsors" -%>
            <section class="sponsors">
              <h4>
                Sponsors
                <% if @bill['sponsors'].size > 5 %>
                  (<%= @bill['sponsors'].size %>)
                <% end %>
              </h4>
              <ul>
                <% @bill.people_and_committee_sponsors(limit: 5).each do |sponsor| %>
                  <li>
                    <% if Person === sponsor %>
                      <div class="depiction">
                        <% if sponsor.image? %>
                          <%= cdn_image_tag(sponsor.image, size: '50x50', alt: '') %>
                        <% else %>
                          <%= image_tag('placeholder.png', size: '50x50', alt: '') %>
                        <% end %>
                      </div>
                      <div class="details">
                        <%= link_to sponsor.name, person_path(@jurisdiction.abbreviation, sponsor) %>
                        <%= district_name(sponsor.most_recent(:district)) %>
                        <span class="sponsor_type"><%= sponsor.type %></span>
                      </div>
                    <% else %>
                      <%= sponsor.name %>
                      <span class="sponsor_type"><%= sponsor.type %></span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
              <% if @bill['sponsors'].size > 5 %>
                <%= link_to 'View all', sponsors_bill_path(@jurisdiction.abbreviation, @bill.id), rel: 'sponsors' %>
              <% end %>
            </section>
          <% end %>

          <% unless @bill['subjects'].blank? %>
            <section>
              <h4>Issue Areas</h4>
              <ul>
                <% @bill['subjects'].each do |subject| %>
                  <li>
                    <%= link_to subject, subject_path(@jurisdiction.abbreviation, subject) %>
                  </li>
                <% end %>
              </ul>
            </section>
          <% end %>
        </aside>
      </div>
    </div>
  </div>
</section>