config/routes.rb
OpenGovernment::Application.routes.draw do
  resources :blurbs

  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'sessions'
  }

  if ENV["SPLASH_AS_HOMEPAGE"]
    root to: 'pages#splash'
    get 'home' => 'pages#index'
  else
    root to: 'pages#index'
  end

  # generate a custom robots.txt
  get 'robots.:format' => 'robots#show'

  get 'widgets/builder' => 'pages#widget_builder'
  get 'splash' => 'pages#splash'
  get 'electeds' => 'pages#splash'
  get 'elected_signup' => 'pages#elected_signup'
  get 'about', to: 'pages#about'
  get 'support', to: 'pages#support'
  get 'faq', to: 'pages#faq'
  get 'honestads', to: 'pages#honestads'
  get 'map', to: 'pages#map'
  get 'terms-of-service', to: 'pages#terms_of_service'
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'candidates', to: 'pages#candidates', as: :candidates_page

  resources :users, only: [:show, :update] do
    member do
      get 'signatures'
    end
  end
  resources :signatures, only: :create
  resources :answers, only: [:create, :edit, :update]

  resources :identities, only: :update

  scope ':jurisdiction' do
    resources :bills, only: [:index, :show] do
      member do
        get 'sponsors'
      end
    end

    resources :people, only: [:index, :show, :update] do
      member do
        get 'bills'
        get 'committees'
        get 'votes'
        get 'ratings'
      end
    end

    resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'preview'
        get 'need_signatures'
        get 'have_answers'
        get 'need_answers'
        get 'recent'
      end

      resources :signatures, only: :index
    end

    resources :subjects, only: [:index, :show]

    match 'overview/lower' => 'pages#lower', as: :lower_overview, via: :get
    match 'overview/upper' => 'pages#upper', as: :upper_overview, via: :get
    match 'overview/bills' => 'pages#bills', as: :bills_overview, via: :get
    match 'overview/meetings' => 'pages#meetings', as: :meetings_overview, via: :get
    match 'overview/votes' => 'pages#key_votes', as: :key_votes_overview, via: :get

    get 'map', to: 'pages#map'

    resources :candidates
  end

  match 'email_upkeep' => 'email_upkeep#index', as: :email_upkeep, via: [:post]

  match 'locator' => 'pages#locator', as: :locator, via: [:get, :post]
  match 'identifier' => 'pages#identifier', as: :identifier, via: :get
  match 'contact_info' => 'pages#contact_info', as: :contact_info, via: :get
  match 'channel' => 'pages#channel', as: :channel, via: :get
  match 'people' => 'people#index', as: :unaffiliated_people, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'people/:id' => 'people#show', as: :unaffiliated_person, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'questions' => 'questions#index', as: :unaffiliated_questions, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match 'questions/:id' => 'questions#show', as: :unaffiliated_question, via: :get, jurisdiction: Metadatum::Unaffiliated::ABBREVIATION
  match ':jurisdiction' => 'pages#overview', as: :jurisdiction, via: :get
end

app/models/candidate.rb
class Candidate < Person
  # useful for finding the current office holder id that candidate opposes
  attr_accessor :current_office_holder_name

  belongs_to :current_office_holder, class_name: "Person", inverse_of: :opponents

  field :party, type: String

  # these are populated by copying fields from current office holder
  field :ocd_division_id, type: String
  field :running_for_position, type: String
  # TODO: this should be really be declared on person
  # but requires some investigation of ramifications
  field :active, type: Boolean, default: false

  before_create :set_active

  # for now, returns no results
  def self.for_location(location)
    location = LocationFormatter.new(location).format
    return where(id: [])
  end

  def political_position_title
    representing_area = metadatum.read_attribute(:name)

    if has_district?
      representing_area += ", District #{current_office_holder.most_recent_district}, "
    end

    "Candidate for #{representing_area} #{running_for_position}"
  end

  private
  def has_district?
    current_office_holder &&
    current_office_holder.respond_to?(:most_recent_district) &&
    current_office_holder.most_recent_district
  end

  def set_active
    write_attribute :active, true
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_filter :force_http

  inherit_resources
  belongs_to :jurisdiction, parent_class: Metadatum, finder: :find_by_abbreviation, param: :jurisdiction

  before_filter :authenticate_user!
  before_filter :check_can_manage_candidates

  def new
    new! do
      if params[:twitter_id]
        screen_name = params[:twitter_id]
        twitter_api = TwitterPersonService.new(screen_name, false)
        match = twitter_api.client.users(screen_name).first
        TwitterPersonAdapter.new(@candidate).run(match)
      end

      if params[:current_office_holder_name]
        matches = Person.active
                  .connected_to(parent.abbreviation)
                  .some_name_matches(params[:current_office_holder_name])

        if matches.any?
          in_office = matches.first
          @candidate.ocd_division_id = in_office.read_attribute(:ocd_division_id)
          @candidate.current_office_holder_name = in_office.full_name
          @candidate.current_office_holder = in_office
          @candidate.running_for_position = in_office.political_position_title
        end
      end
    end
  end

  def edit
    edit! do
      @candidate.current_office_holder_name = @candidate.current_office_holder.full_name
      logger.debug(self.inspect)
    end
  end

  def create
    create! { candidates_path parent }
  end

  def update
    update! { candidates_path parent }
  end

  def destroy
    destroy! { candidates_path parent }
  end

  private
  def check_can_manage_candidates
    unless current_user.can?(:manage_candidates)
      raise Authority::SecurityViolation.new(current_user,
                                             :manage_candidates,
                                             CandidatesController)
    end
  end

  def end_of_association_chain
    Candidate.connected_to(parent.abbreviation)
  end
end

app/views/candidates/_form.html.erb
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :ocd_division_id, as: :hidden %>
  <%= f.input :current_office_holder_id, as: :hidden %>
  <%= f.input :state, as: :hidden, value: parent.abbreviation %>

  <label for="twitter_id">Twitter</label>
  <%= f.text_field :twitter_id, placeholder: "Load from which twitter account?" %>

  <label for="current_office_holder_name">Current office holder</label>
  <%= f.text_field :current_office_holder_name, placeholder: "Current office holder's name?" %>

  <label for="running_for_position">Office</label>
  <%= f.text_field :running_for_position, placeholder: "Which office is the candidate running for?" %>

  <label for="full_name">Full name</label>
  <%= f.text_field :full_name, placeholder: "Full Name" %>

  <label for="email">Email</label>
  <%= f.text_field :email, placeholder: "Email" %>

  <label for="photo_url">URL for avatar image</label>
  <%= f.text_field :photo_url, placeholder: "URL for avatar image" %>

  <label for="party">Party affiliation</label>
  <%= f.text_field :party, placeholder: "Party" %>
</div>

<div class="form-actions">
  <%= f.button :submit, class: "cta-pill" %>
</div>

app/views/candidates/_managed_candidate.html.erb
<li>
  <div class="candidate-display manage-candidates-candidate-summary">
    <%- if managed_candidate.active? %>
      <div class="candidate-active">Active</div>
    <%- end %>

    <div class="emph">
      <div class="avatar">
        <%- if managed_candidate.photo_url? %>
          <%= cdn_image_tag(managed_candidate.photo_url, size: "60x60", alt: "") %>
        <%- end %>
      </div>
      <div class="candidate-headline manage-candidate-full-name"><%= managed_candidate.full_name %></div>
    </div>
  </div>
  <div class="manage-actions">
    Actions:
    <ul>
      <!-- <li><%= link_to "Show", candidate_path(parent, managed_candidate) %></li> -->
      <li><%= link_to "Edit", edit_candidate_path(parent, managed_candidate) %></li>
      <li><%= link_to "Destroy", candidate_path(parent, managed_candidate), method: :delete, data: { confirm: "Are you sure?" } %></li>
    </ul>
  </div>
</li>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= simple_form_for(@candidate, url: candidate_path(parent, @candidate)) do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>

<div class="manage-candidates-navigation">
  <%= link_to "Show", candidate_path(parent, @candidate) %> |
  <%= link_to "Back", candidates_path(parent) %>
</div>

app/views/candidates/index.html.erb
<h1>Candidates</h1>

<ul class="manage-candidates-list">
  <%= render partial: "managed_candidate", collection: @candidates %>
  <li>
    <%= form_tag new_candidate_path, method: "get", class: "pre-populate-candidate-form" do -%>
      <%= label_tag :twitter_id, "Twitter id:" %>
      <%= text_field_tag :twitter_id %>

      <%= label_tag :current_office_holder_name, "Name of current office holder:" %>
      <%= text_field_tag :current_office_holder_name %>

      <%= submit_tag "New Candidate", class: "cta-pill" %>
    <% end -%>
  </li>
  <!-- <li><%= link_to "New Candidate", new_candidate_path %></li> -->
</ul>

app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= simple_form_for resource do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>

<div class="manage-candidates-navigation">
  <%= link_to "Back", candidates_path %>
</div>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>